name: Droplet Deployer

on:
  push:
    branches: [deploy-production]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Deploy and restart server
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          PASSWORD_SALT: ${{secrets.PASSWORD_SALT}}
        run: |
          cd server
          yarn
          PORT=80 ENV=production yarn start:prod
